---
title: "Data Import"
output: github_document
---

```{r setup}
library(tidyverse)
library(readxl)

```

## Read in some data

Read in the litters dataset

```{r}
litters_df = read_csv('./data/FAS_litters.csv')
litters_df = janitor::clean_names(litters_df)  #clean_names function in janitor package
```


##Take a look at the data

Pringting in the console
```{r}
litters_df
```

```{r}
tail(litters_df)
```


```{r}
skimr::skim(litters_df)
```

## Options to read_csv

check out '?read_csv' for more information.

```{r}
litters_df = read_csv('./data/FAS_litters.csv', skip = 10, col_names = FALSE)
```

```{r}
litters_df = read_csv('./data/FAS_litters.csv', na = c('', 'NA', '999'))
```

## Other file formats

Read in an excel file

```{r}
mlb_df = read_excel('./data/mlb11.xlsx', range = 'A1:F7')
mlb_df
```

Read in a SASfile
```{r}
pulse_df = haven::read_sas('./data/public_pulse_data.sas7bdat')
pulse_df 
```

##Comparison with Base R

what about `read.csv`...?

```{r}
litters_base = read.csv('data/FAS_litters.csv')
litters_readr = read_csv('data/FAS_litters.csv')

litters_base
litters_readr
```


##Exporting data

Export the mlb sun_table.

```{r}
write_csv(mlb_df, './data/mlb_subtable.csv')
```

